# Generated by Django 3.0.6 on 2020-06-08 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mini',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod', models.IntegerField(verbose_name='Cod')),
                ('datetime', models.CharField(max_length=100, verbose_name='Datetime')),
                ('time_series', models.FloatField(verbose_name='Series')),
            ],
        ),
    ]
